### ISSUE TITLE
Some tests seem to fail!

### ISSUE THREAD

**Issue by bobbybouwmann** [madhums/node-express-mongoose-demo#121]
Hi, if I run the tests they fail! I can't seem to find the problem :(
```
POST /users
  Invalid parameters
    1) no email - should respond with errors
    2) no name - should respond with errors
    ✓ should not save the user to the database 

13 passing (263ms)
2 failing
```

This is the error message:
```
1) Users POST /users Invalid parameters no email - should respond with errors:

  at error (/vagrant_data/authenication/node_modules/supertest/lib/test.js:235:13)
  at Test.assert (/vagrant_data/authenication/node_modules/supertest/lib/test.js:177:23)
  at Server.assert (/vagrant_data/authenication/node_modules/supertest/lib/test.js:132:12)
  at Server.g (events.js:180:16)
  at Server.EventEmitter.emit (events.js:92:17)
  at net.js:1273:10
  at process._tickCallback (node.js:415:13)
```
```
2) Users POST /users Invalid parameters no name - should respond with errors:

  at error (/vagrant_data/authenication/node_modules/supertest/lib/test.js:235:13)
  at Test.assert (/vagrant_data/authenication/node_modules/supertest/lib/test.js:177:23)
  at Server.assert (/vagrant_data/authenication/node_modules/supertest/lib/test.js:132:12)
  at Server.g (events.js:180:16)
  at Server.EventEmitter.emit (events.js:92:17)
  at net.js:1273:10
  at process._tickCallback (node.js:415:13)
```

**Comment by madhums** [comment]
Have fixed the tests, should be working now.
