### ISSUE TITLE
Cannot find module 'config'

### ISSUE THREAD

**Issue by cc17** [madhums/node-express-mongoose-demo#123]
i can't solve this problem. hope you can fix it for me.thanks.
this is error message:

module.js:340
    throw err;
          ^
Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/chengchi/Dev/h2h_new/server.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by hugoperier** [comment]
yes
