### ISSUE TITLE
passport error -- google oauth2

### ISSUE THREAD

**Issue by AaronJin2013** [madhums/node-express-mongoose-demo#137]
I have use 'npm install' ,it's successed.

then ,I use 'npm start', it's throw Error,

node-express-mongoose-demo/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66
  if (!options.clientID) throw new Error('OAuth2Strategy requires a clientID o
                               ^
Error: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/aaron.jin/code/node-express-mongoose-demo/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66:32)
    at new Strategy (/Users/aaron.jin/code/node-express-mongoose-demo/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:48:18)
    at Object.<anonymous> (/Users/aaron.jin/code/node-express-mongoose-demo/config/passport/google.js:15:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/aaron.jin/code/node-express-mongoose-demo/config/passport.js:11:14)

I can't fix it, do you help me?

**Comment by madhums** [comment]
You need to copy `config/env/env.example.json` to `config/env/env.json`

From README.md

> NOTE: Do not forget to set the facebook, twitter, google, linkedin and github CLIENT_IDs and SECRETs. In development env, you can simply copy config/env/env.example.json to config/env/env.json and just replace the values there
