### ISSUE TITLE
when I npm start....

### ISSUE THREAD

**Issue by Klchan-me** [madhums/node-express-mongoose-demo#141]
nodejs-express-mongoose-demo@4.0.0 start /project/application/node-demo
> NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/nodemon server.js

4 Aug 17:22:40 - [nodemon] v1.3.7
4 Aug 17:22:40 - [nodemon] to restart at any time, enter `rs`
4 Aug 17:22:40 - [nodemon] watching: *.*
4 Aug 17:22:40 - [nodemon] starting `node --harmony server.js`
/project/application/node-demo/node_modules/mongoose/lib/index.js:111
  var queryStringStart = uri.indexOf('?');
                             ^
TypeError: uri.indexOf is not a function
    at checkReplicaSetInUri (/project/application/node-demo/node_modules/mongoose/lib/index.js:111:30)
    at Mongoose.connect (/project/application/node-demo/node_modules/mongoose/lib/index.js:220:40)
    at connect (/project/application/node-demo/server.js:24:12)
    at Object.<anonymous> (/project/application/node-demo/server.js:26:1)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3
4 Aug 17:22:41 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by madhums** [comment]
can you try without the --harmony flag?

**Comment by bastienSchaeffer** [comment]
Hi Madhusudhan,

sure I will try in 6 hours exactly since this is an evening job for me,
many thanks for your help on this.

Kind regards,

Bastien

2015-08-04 11:27 GMT+02:00 Madhusudhan Srinivasa <notifications@github.com>:

> can you try without the --harmony flag?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madhums/node-express-mongoose-demo/issues/141#issuecomment-127540291>
> .
>



-- 
*Bastien Schaeffer*
Front-end developer / Web designer
http://bast-dot.com

**Comment by madhums** [comment]
`npm start` should work.
