### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by x7LoveLin** [madhums/node-express-mongoose-demo#173]
const { wrap: async = require('co');
                                   ^

SyntaxError: Unexpected token ;

**Comment by x7LoveLin** [comment]
const { wrap: async } = require('co');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\linqz\WebstormProjects\node-express-mongoose-demo\config\routes.js:10:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\linqz\WebstormProjects\node-express-mongoose-demo\server.js:40:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by madhums** [comment]
What version of node are you using? 

You need node >=6.x

**Comment by jtbarker** [comment]
I have node dev version 6.x and am getting this error too.
