### ISSUE TITLE
i debug by webstorm ，a problem occur

### ISSUE THREAD

**Issue by shijianmei** [madhums/node-express-mongoose-demo#236]
/usr/local/bin/node --debug-brk=61458 --expose_debug_as=v8debug /Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/server.js
Debugger listening on port 61458
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/server.js:13:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/config/passport/google.js:16:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jianmei/Documents/NodeJs/node-express-mongoose-demo/config/passport.js:11:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Process finished with exit code 1

**Comment by shijianmei** [comment]
I have solved it，cp .env.example .env

**Comment by madhums** [comment]
Yes, this is mentioned in the readme and in setup instructions.
