### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by TalArbatov** [madhums/node-express-mongoose-demo#325]
doesnt seem to work after 'npm install'

i tried 'npm start' cause thats what I saw in package.json to start the development server.

sorry If i didnt understand something, im new to git and trying it out.

EDIT: full command line error:

$ npm start

> nodejs-express-mongoose-demo@4.0.0 start X:\Development\React\node-express-mongoose-demo
> cross-env NODE_ENV=development ./node_modules/.bin/nodemon server.js

[nodemon] 1.14.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
X:\Development\React\node-express-mongoose-demo\node_modules\passport-oauth2\lib\strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (X:\Development\React\node-express-mongoose-demo\node_modules\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (X:\Development\React\node-express-mongoose-demo\node_modules\passport-google-oauth20\lib\strategy.js:52:18)
    at Object.<anonymous> (X:\Development\React\node-express-mongoose-demo\config\passport\google.js:16:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (X:\Development\React\node-express-mongoose-demo\config\passport.js:11:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Blueblau** [comment]
This is the same as #323

**Comment by TalArbatov** [comment]
thank you, I'll close the issue
