### ISSUE TITLE
(node:54610) UnhandledPromiseRejectionWarning: MongoError: not authorized

### ISSUE THREAD

**Issue by saifeiLee** [madhums/node-express-mongoose-demo#353]
When I run `npm start`, I got an error:
```sh
(node:54673) UnhandledPromiseRejectionWarning: MongoError: not authorized on noobjs_dev to execute command { insert: "system.indexes", ordered: true, $db: "noobjs_dev" }
    at Function.MongoError.create (/Users/waltermitty/Code/JavaScript/node-learning/node-express-mongoose-demo/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/waltermitty/Code/JavaScript/node-learning/node-express-mongoose-demo/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/waltermitty/Code/JavaScript/node-learning/node-express-mongoose-demo/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/waltermitty/Code/JavaScript/node-learning/node-express-mongoose-demo/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/waltermitty/Code/JavaScript/node-learning/node-express-mongoose-demo/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:54673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any help please?

**Comment by sandeepperkariappdev** [comment]
here is the solution

https://stackoverflow.com/questions/49101567/mongodb-atlas-not-authorized-on-admin-to-execute-command

https://stackoverflow.com/questions/49179829/cannot-read-write-on-a-mongodb-atlas-database-using-mongoose/49181821#49181821

**Comment by sandeepperkariappdev** [comment]
On mongodb atlas we select nodejs driver version 2.2 or later it works
